const curatedPools = {
  tokyo: [
    { name: "Senso-ji Temple", description: "Tokyo's oldest and most famous Buddhist temple, located in Asakusa.", category: "culture", cost: 0 },
    { name: "Tokyo Tower", description: "Visit the iconic red-and-white communications tower and enjoy panoramic city views.", category: "sightseeing", cost: 1200 },
    { name: "Meiji Jingu Shrine", description: "Walk through the forested grounds of this serene Shinto shrine dedicated to Emperor Meiji.", category: "culture", cost: 0 },
    { name: "Shinjuku Gyoen National Garden", description: "Stroll through beautiful Japanese traditional, English, and French landscaped gardens.", category: "nature", cost: 500 },
    { name: "Ueno Park", description: "Explore the spacious public park housing the Tokyo National Museum and Ueno Zoo.", category: "culture", cost: 600 },
    { name: "Tsukiji Outer Market", description: "Savor fresh seafood, street food, and kitchen tools at this vibrant historic marketplace.", category: "dining", cost: 1500 },
    { name: "Odaiba Marine Park", description: "Walk along the waterfront beach offering views of the Rainbow Bridge and the Statue of Liberty.", category: "sightseeing", cost: 0 },
    { name: "Takeshita Street", description: "Browse trendy fashion boutiques, colorful crepe stands, and quirky stores.", category: "shopping", cost: 500 },
    { name: "Tokyo Skytree", description: "Ascend the tallest structure in Japan for breathtaking views of the Kanto region.", category: "sightseeing", cost: 3100 },
    { name: "Akihabara", description: "Discover the hub for electronics, anime shops, manga stores, and maid cafes.", category: "culture", cost: 1000 },
    { name: "Imperial Palace", description: "Walk through the historic castle ruins and pristine gardens of the imperial family residence.", category: "sightseeing", cost: 0 },
    { name: "Ginza Six", description: "Explore luxury boutiques, rooftop gardens, and contemporary art installations.", category: "shopping", cost: 2000 },
    { name: "Roppongi Hills", description: "Visit the contemporary art museum and the open-air sky deck observation platform.", category: "culture", cost: 2200 },
    { name: "Yoyogi Park", description: "Relax in one of Tokyo's largest parks, popular for street performances and ginkgo forests.", category: "nature", cost: 0 },
    { name: "Sumida Aquarium", description: "Visit the modern indoor aquarium housing penguins, fur seals, and jellyfish displays at Tokyo Skytree Town.", category: "nature", cost: 2300 },
    { name: "Zojo-ji Temple", description: "Tour the historic Buddhist temple situated next to Tokyo Tower, holding the Tokugawa clan graves.", category: "culture", cost: 0 },
    { name: "Nezu Museum", description: "Explore traditional Japanese and East Asian art collections set inside a tranquil garden estate.", category: "culture", cost: 1300 },
    { name: "Tokyo Metropolitan Government Building", description: "Ascend the free observation decks in Shinjuku for stunning panoramic views of Tokyo and Mount Fuji.", category: "sightseeing", cost: 0 }
  ],
  goa: [
    { name: "Calangute Beach", description: "Relax at Goa's most famous and lively beach strip, popular for water sports and shacks.", category: "nature", cost: 0 },
    { name: "Fisherman's Cove, Candolim", description: "Indulge in authentic Goan fish curry, tandoori specialties, and cold drinks with live music.", category: "dining", cost: 800 },
    { name: "Fort Aguada", description: "Explore the 17th-century Portuguese lighthouse and fort overlooking the Arabian Sea.", category: "sightseeing", cost: 0 },
    { name: "Basilica of Bom Jesus", description: "Visit the UNESCO World Heritage site holding the mortal remains of St. Francis Xavier.", category: "culture", cost: 0 },
    { name: "Viva Panjim", description: "Dine on traditional Indo-Portuguese Goan vindaloo and cafreal in a heritage home setting.", category: "dining", cost: 600 },
    { name: "Fontainhas", description: "Walk through the historic colorful Portuguese-style houses and narrow winding alleys of Panaji.", category: "culture", cost: 0 },
    { name: "Anjuna Flea Market", description: "Shop for spices, clothes, jewelry, and handicrafts at this famous beachside market.", category: "shopping", cost: 500 },
    { name: "Curlies, Anjuna", description: "Sip drinks and watch the sunset at one of Goa's original and most iconic beachfront shacks.", category: "dining", cost: 1000 },
    { name: "Chapora Fort", description: "Climb the red laterite ramparts made famous by Bollywood films, offering panoramic estuary views.", category: "sightseeing", cost: 0 },
    { name: "Sahakari Spice Farm", description: "Take a guided walk through aromatic vanilla, cardamon, and black pepper farms with a traditional lunch.", category: "nature", cost: 500 },
    { name: "Dudhsagar Waterfalls", description: "Marvel at the spectacular four-tiered waterfall cascading down the Western Ghats forest.", category: "nature", cost: 1500 },
    { name: "Arambol Beach", description: "Visit the relaxed beach in North Goa, known for its sweet water lake, drum circles, and bohemian vibe.", category: "nature", cost: 0 },
    { name: "Mangueshi Temple", description: "Explore the landmark 450-year-old temple dedicated to Lord Manguesh in Priol.", category: "culture", cost: 0 },
    { name: "Reis Magos Fort", description: "Tour the beautifully restored 16th-century fortress situated on the Mandovi River banks.", category: "culture", cost: 300 },
    { name: "Our Lady of the Immaculate Conception Church", description: "Admire the landmark baroque church with its symmetric double staircase in Panaji.", category: "culture", cost: 0 },
    { name: "Mapusa Market", description: "Experience the bustling traditional weekly market filled with spices, pickles, coir mats, and fresh produce.", category: "shopping", cost: 200 }
  ],
  mussoorie: [
    { name: "Mussoorie Mall Road", description: "Stroll along the bustling pedestrian-only promenade lined with shops, cafes, and mountain views.", category: "shopping", cost: 200 },
    { name: "Kalsang Friends Corner", description: "Enjoy authentic Tibetan momos, thukpa, and Chinese dishes in a vibrant red-lit diner.", category: "dining", cost: 500 },
    { name: "Gun Hill Mussoorie", description: "Take the cable car ride up to the second highest peak in Mussoorie for Himalayan views.", category: "sightseeing", cost: 150 },
    { name: "Kempty Falls", description: "Splash in the cool water pools beneath the popular giant waterfall cascading down the valley.", category: "nature", cost: 100 },
    { name: "Company Garden", description: "Relax among manicured flowerbeds, fountains, a small lake with paddleboats, and nursery plants.", category: "nature", cost: 50 },
    { name: "Lal Tibba", description: "View the snow-covered Himalayan peaks through telescopes at Landour's highest lookout.", category: "sightseeing", cost: 100 },
    { name: "Landour Bakehouse", description: "Savor fresh cinnamon rolls, gingerbread, and coffee in a historic British-era bakery.", category: "dining", cost: 400 },
    { name: "Sisters Bazaar", description: "Visit the quiet woodland market famous for homemade cheese, jams, and peanut butter.", category: "shopping", cost: 300 },
    { name: "George Everest House", description: "Explore the renovated estate of the Surveyor General of India with panoramic valley views.", category: "sightseeing", cost: 0 },
    { name: "Jharipani Falls", description: "Take a pleasant nature hike down to the scenic and secluded waterfall near Jharipani village.", category: "nature", cost: 0 },
    { name: "Cloud End", description: "Walk through dense oak and deodar forests to reach this historic 1838 heritage bungalow estate.", category: "nature", cost: 100 },
    { name: "Mussoorie Lake", description: "Enjoy pedal boating and snacks at the scenic artificial lake along the Dehradun-Mussoorie road.", category: "nature", cost: 100 },
    { name: "Camel's Back Road", description: "Take a peaceful 3km walk under towering pine trees, named after a camel-shaped rock formation.", category: "sightseeing", cost: 0 },
    { name: "Bhadraj Temple", description: "Embark on a scenic day trek to the hilltop temple dedicated to Lord Balbhadra.", category: "adventure", cost: 0 }
  ],
  paris: [
    { name: "Eiffel Tower", description: "Ascend the iconic wrought-iron lattice monument for sweeping views of Paris.", category: "sightseeing", cost: 2500 },
    { name: "Louvre Museum", description: "See world-renowned art collections including the Mona Lisa and Venus de Milo.", category: "culture", cost: 2200 },
    { name: "Notre-Dame Cathedral", description: "Admire the French Gothic architecture and historic gargoyles on the Île de la Cité.", category: "culture", cost: 0 },
    { name: "Arc de Triomphe", description: "Visit the monumental arch honoring those who fought for France, at the end of the Champs-Élysées.", category: "sightseeing", cost: 1300 },
    { name: "Sacre-Coeur", description: "Take in the panoramic views of Paris from the steps of the white stone church in Montmartre.", category: "culture", cost: 0 },
    { name: "Seine River", description: "Enjoy a scenic boat cruise past the Louvre, Notre-Dame, and illuminated historical bridges.", category: "sightseeing", cost: 1500 },
    { name: "Musee d'Orsay", description: "Explore the vast impressionist art collections housed in a grand former railway station.", category: "culture", cost: 1600 },
    { name: "Jardin du Luxembourg", description: "Walk through the beautifully manicured lawns, statues, and octagonal grand basin pond.", category: "nature", cost: 0 },
    { name: "Tuileries Garden", description: "Stroll the public gardens connecting the Louvre Museum to the Place de la Concorde.", category: "nature", cost: 0 },
    { name: "Palais Garnier", description: "Tour the opulent 19th-century opera house, famous for its grand marble staircase and chandelier.", category: "culture", cost: 1500 },
    { name: "Centre Pompidou", description: "Browse masterworks of modern and contemporary art in the high-tech architectural landmark.", category: "culture", cost: 1500 },
    { name: "Panthéon", description: "Visit the neoclassical mausoleum in the Latin Quarter containing the tombs of Victor Hugo and Voltaire.", category: "culture", cost: 1100 },
    { name: "Champs-Élysées", description: "Stroll the famous avenue lined with luxury flagship stores, theatres, and cafes.", category: "shopping", cost: 1000 }
  ],
  mumbai: [
    { name: "Gateway of India", description: "View the grand basalt arch constructed in 1924 overlooking the Arabian Sea harbor.", category: "sightseeing", cost: 0 },
    { name: "Marine Drive", description: "Stroll the arc-shaped coastal boulevard known as the Queen's Necklace for sunset views.", category: "nature", cost: 0 },
    { name: "Chhatrapati Shivaji Maharaj Terminus", description: "Admire the spectacular Victorian Gothic Revival railway station and UNESCO World Heritage site.", category: "culture", cost: 0 },
    { name: "Elephanta Caves", description: "Take a ferry to the island to explore the rock-cut cave temples dedicated to Shiva.", category: "culture", cost: 300 },
    { name: "Haji Ali Dargah", description: "Walk along the narrow causeway to the stunning floating mosque and tomb in the ocean.", category: "culture", cost: 0 },
    { name: "Siddhivinayak Temple", description: "Visit the highly revered Hindu temple dedicated to Lord Ganesha in Prabhadevi.", category: "culture", cost: 0 },
    { name: "Juhu Beach", description: "Walk along the popular beach and sample Mumbai street food like Pav Bhaji and Bhel Puri.", category: "nature", cost: 200 },
    { name: "Crawford Market", description: "Shop for fruits, vegetables, spices, and pets in the historic Victorian-era covered market.", category: "shopping", cost: 100 },
    { name: "Colaba Causeway", description: "Browse vibrant street shops selling clothes, handicrafts, brass items, and incense.", category: "shopping", cost: 300 },
    { name: "Sanjay Gandhi National Park", description: "Explore the massive urban forest, visit Kanheri Caves, and take a mini-train safari.", category: "nature", cost: 200 },
    { name: "Nehru Planetarium", description: "Attend interactive astronomical shows and science exhibitions in Worli.", category: "culture", cost: 100 }
  ],
  chicago: [
    { name: "Millennium Park", description: "Explore the downtown park featuring the Cloud Gate sculpture and Crown Fountain.", category: "sightseeing", cost: 0 },
    { name: "Art Institute of Chicago", description: "Visit the world-class museum famous for its impressionist and post-impressionist collections.", category: "culture", cost: 2500 },
    { name: "Chicago Riverwalk", description: "Stroll the pedestrian path lined with bars, cafes, public art, and towering architecture.", category: "sightseeing", cost: 0 },
    { name: "Navy Pier", description: "Take a ride on the Centennial Wheel and explore lakefront parks, shops, and restaurants.", category: "sightseeing", cost: 300 },
    { name: "Shedd Aquarium", description: "Visit the massive indoor public aquarium home to beluga whales, dolphins, and penguins.", category: "nature", cost: 3500 },
    { name: "Field Museum", description: "Discover natural history exhibits and see SUE, the world's most complete T. Rex skeleton.", category: "culture", cost: 2600 },
    { name: "Willis Tower", description: "Step onto The Ledge, a glass balcony extending 4 feet outside the 103rd floor of the iconic tower.", category: "sightseeing", cost: 3500 },
    { name: "Lincoln Park Zoo", description: "Stroll the historic free public zoo and glass conservatory greenhouses in Lincoln Park.", category: "nature", cost: 0 },
    { name: "Buckingham Fountain", description: "Marvel at the giant rococo-style fountain in Grant Park featuring dramatic water shows.", category: "sightseeing", cost: 0 }
  ]
};

module.exports = curatedPools;
